paths:
  /api/products/:
    get:
      summary: Obtener todos los productos de la DB
      tags:
        - Products
      responses:
        "200":
          description: Si tiene éxito, devuelva todos los productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/products'   
        "500":
          description: Si no tiene éxito, devolver mensaje de error
    post:
      summary: Crear un nuevo producto en la DB
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestsBodies/products'   
      responses:
        "200": 
          description: Si tiene éxito, devuelva PRODUCTO CREADO CORRECTAMENTE
        "500":
          description: Si no tiene éxito, devolver mensaje de error
  /api/products/{productID}:  
    get:
      summary: Obtener un solo producto de la base de datos
      tags:
        - Products
      parameters:
        - name: productID
          in: path  
          required: true
          description: Product ID to fetch
          schemas:
            type: string
      responses:
        "200":
          description: Si tiene éxito, devolver un solo producto 
        "500":
          description: Si no tiene éxito, devolver mensaje de error
    put:
      summary: Actualizar un solo producto de la DB 
      tags:
        - Products
      parameters:
        - name: productID
          in: path  
          required: true
          description: Product ID to fetch
          schemas:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestsBodies/products'        
      responses:
        "200":
          description: Si tiene éxito, devolver producto actualizado
        "500":
          description: Si no tiene éxito, devolver mensaje de error
    delete:
      summary: Eliminar un solo producto de la DB 
      tags:
        - Products
      parameters:
        - name: productID
          in: path  
          required: true
          description: Product ID to fetch
          schemas:
            type: string  
      responses:
        "200":
          description: Si tiene éxito, devolver producto eliminado 
        "500":
          description: Si no tiene éxito, devolver mensaje de error
components:
  schemas:
    products:
      type: object 
      properties:
        id:     
          type: objectId
          description: Mongo Id  
        title: 
          type: string
          description: Product titles
        description:
          type: string
          description: Product description
        price: 
          type: number
          description: Product price
        thumbnail: 
          type: array of pictures
          description: Product thumbnail
        status:
          type: boolean
          description: Product status
        category:
          type: string
          description: Product category
        code: 
          type: string
          description: Product code
        stock: 
          type: number
          description: Product stock
        owner: 
          type: string
          description: Quién creó el producto    
      example:
          id: objectsId(123dewq314)
          title: Product title
          description: Product description
          price: 10
          thumbnail: [./images/]
          status: true
          category: products
          code: products123
          stock: 4
          owner: mail@owner or admin
  requestsBodies:
    products:
      type: object 
      properties:  
        title: 
          type: string
          description: Product titles
        description:
          type: string
          description: Product description
        price: 
          type: number
          description: Product price
        thumbnail: 
          type: array of pictures
          description: Product thumbnail
        category:
          type: string
          description: Product category
        code: 
          type: string
          description: Product code
        stock: 
          type: number
          description: Product stock
        owner: 
          type: string
          description: Quién creó el producto
      example:
        title: product
        price: 3
        thumbnail: [./images/]
        category: products
        code: products123
        stock: 5
        owner: exaple@mail